-- Generated by the Organizer Library (Thu Feb 20 19:33:31 2025)
return {
    [1]={
        ["log_name"]="tali'ah gages +1", 
        ["id"]=25813, 
        ["name"]="tali'ah gages +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="tali'ah turban +1", 
        ["id"]=25591, 
        ["name"]="tali'ah turban +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="queller rod", 
        ["id"]=21084, 
        ["name"]="queller rod", 
        ["count"]=1
    }
}