-- Generated by the Organizer Library (Thu Feb 20 19:33:31 2025)
return {
    [1]={
        ["log_name"]="lucidity sash", 
        ["id"]=28416, 
        ["name"]="lucidity sash", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="sancus sachet", 
        ["id"]=21394, 
        ["name"]="sancus sachet", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="vox grip", 
        ["id"]=19058, 
        ["name"]="vox grip", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="evoker's ring", 
        ["id"]=14625, 
        ["name"]="evoker's ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="caller's pendant", 
        ["id"]=11619, 
        ["name"]="caller's pendant", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="convoker's pigaches", 
        ["id"]=28237, 
        ["name"]="con. pigaches", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="campestres's cape", 
        ["id"]=26260, 
        ["name"]="campestres's cape", 
        ["count"]=1
    }
}