-- Generated by the Organizer Library (Thu Feb 20 19:33:31 2025)
return {
    [1]={
        ["log_name"]="tali'ah seraweels +1", 
        ["id"]=25872, 
        ["name"]="tali'ah sera. +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="witful belt", 
        ["id"]=10826, 
        ["name"]="witful belt", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="varar ring", 
        ["id"]=26179, 
        ["name"]="varar ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="varar ring", 
        ["id"]=26179, 
        ["name"]="varar ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="tali'ah manteel +2", 
        ["id"]=25796, 
        ["name"]="tali'ah manteel +2", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }
}